# Generated by Django 3.1.6 on 2023-11-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_longa',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao_curta',
        ),
    ]
