# Generated by Django 3.1.6 on 2023-11-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20231124_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
    ]
