# Generated by Django 4.2.7 on 2023-11-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(null=True),
        ),
    ]
